# We create a dataframe of new fixed image data of embryos with the nuclei pre-segmented and p cell identified.

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import os
# import json
%matplotlib inline

In [ ]:
np.version.version

# Read the nstats files from folder Ncoords_1_txt

### Implementation note: after reading all files, they are put into a dataframe (df_reduced) in a sequential order based on the order in which the folders were accessed.

In [3]:
working_path = 'Ncoords_1_txt//'

In [4]:
entries = os.listdir(working_path)

In [ ]:
# check that num entries == 4*number of embryos in dataset
%whos

In [ ]:
# nstats dataframe per experiment - takes ~1h for 42 embryos
df_nstats = []
for file_name in entries:
    # print(file_name)
    if file_name.startswith('nstats')==True:
        # print(file_name)
        # print(file_name[0:-4])
        df_name = ''.join(file_name[0:-4])
        full_name = working_path[0:-1]+df_name+'.txt'
        #df_name_new = ''.join(working_path[0:-1]+file_name[6:-4])
        df_name_new = ''.join(file_name[6:-4])
        print(df_name_new)
#     pd.read_csv("../data_folder/data.csv")
        temp_df = pd.read_csv(full_name, delimiter=',')
        temp_df.insert(1, "sample_id", df_name_new, True)
        df_nstats.append(temp_df)

In [ ]:
# check for correct number of samples
len(df_nstats)

In [8]:
keep_columns = ['Volume', 'sample_id', 'Centroid_1', 'Centroid_2', 'Centroid_3', 'ConvexVolume', 'EquivDiameter']

In [9]:
df_nstats[0]

,Volume,sample_id,Centroid_1,Centroid_2,Centroid_3,BoundingBox_1,BoundingBox_2,BoundingBox_3,BoundingBox_4,BoundingBox_5,...,ConvexImage_139658,ConvexImage_139659,ConvexImage_139660,ConvexImage_139661,ConvexImage_139662,ConvexImage_139663,ConvexImage_139664,ConvexVolume,Solidity,SurfaceArea
0,80829,Sample8FOV1,218.348699,221.575746,43.843596,190.5,194.5,22.5,55,56,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85909,0.940868,9472.502541
1,78048,Sample8FOV1,200.770013,99.474285,50.248104,173.5,70.5,29.5,56,58,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,82737,0.943326,9284.051225
2,67871,Sample8FOV1,110.395353,225.418942,49.415170,80.5,197.5,30.5,58,56,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71504,0.949192,8532.483552
3,62989,Sample8FOV1,126.759323,121.682992,57.744193,99.5,94.5,39.5,55,54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64928,0.970136,7851.981881
4,56679,Sample8FOV1,121.213783,315.551898,62.004058,95.5,289.5,44.5,52,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58703,0.965521,7365.616005
5,21642,Sample8FOV1,174.823168,302.920155,62.287543,159.5,280.5,49.5,38,41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29338,0.737678,4877.438532
6,30237,Sample8FOV1,192.219202,292.856897,74.915435,171.5,272.5,58.5,39,40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32600,0.927515,4982.531864
7,55046,Sample8FOV1,268.002943,153.067544,75.010428,242.5,128.5,57.5,52,49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56966,0.966296,7185.728930
8,17277,Sample8FOV1,192.525844,205.755397,81.431730,178.5,187.5,64.5,35,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27987,0.617322,4765.903111
9,30612,Sample8FOV1,215.993336,205.345061,81.246407,199.5,186.5,65.5,36,37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32318,0.947212,5081.706965
10,54093,Sample8FOV1,237.755625,70.091287,86.378829,213.5,44.5,68.5,49,50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55844,0.968645,7098.193068
11,47816,Sample8FOV1,124.795466,267.415593,90.298833,102.5,244.5,71.5,46,48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49570,0.964616,6543.010818
12,57601,Sample8FOV1,179.590858,108.040156,89.887189,154.5,84.5,66.5,48,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62024,0.928689,7558.751874
13,44089,Sample8FOV1,103.687791,179.546894,91.684230,79.5,156.5,75.5,47,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45710,0.964537,6226.344675

In [10]:
from copy import copy, deepcopy

working_path = 'Ncoords_1_txt//'
entries = os.listdir(working_path)

df_reduced = []
count = 1
for df_temp in df_nstats:
#     print(count)
    count += 1
    df_t = deepcopy(df_temp)
    df_t = df_t[keep_columns]
#     print(df_temp.loc[0, 'sample_id'][6:])
#     print('name')
#     print('pcellnucID'+df_temp.loc[0, 'sample_id'][6:] + '.txt')
    for file_name in entries:
#         print(file_name)
#         if df_temp.loc[0, 'sample_id'][6:] == 'Sample17FOV1':
#             print(file_name)
        if file_name == 'pcellnucID' + df_temp.loc[0, 'sample_id'][:] + '.txt':
#             print('here', df_temp.loc[0, 'sample_id'][6:])
            
            temp_name = working_path[0:-1]+'pcellnucID'+df_temp.loc[0, 'sample_id'][:] + '.txt'
            csv_name = 'dataset1_'+df_temp.loc[0, 'sample_id'][:]+'.csv'
#         if file_name.startswith('pcellnucIDSample')==True and temp_name == :
# print(temp_name)
            df_pcell = pd.read_csv(temp_name, delimiter=',', header = None)
            df_t['Pcell_id'] = df_pcell.loc[0,0].item()
    df_t["cell_name"] = df_t.index + 1
    df_reduced.append(df_t)
    # Save
#    df_t.to_csv(csv_name, index=False)

In [ ]:
file_name

In [ ]:
df_temp.loc[0, 'sample_id'][:]

In [13]:
# Save
# np.save('df_reduced_1.npy', df_reduced)

In [14]:
df_reduced[0]

,Volume,sample_id,Centroid_1,Centroid_2,Centroid_3,ConvexVolume,EquivDiameter,Pcell_id,cell_name
0,80829,Sample8FOV1,218.348699,221.575746,43.843596,85909,53.644211,5,1
1,78048,Sample8FOV1,200.770013,99.474285,50.248104,82737,53.021790,5,2
2,67871,Sample8FOV1,110.395353,225.418942,49.415170,71504,50.609092,5,3
3,62989,Sample8FOV1,126.759323,121.682992,57.744193,64928,49.365328,5,4
4,56679,Sample8FOV1,121.213783,315.551898,62.004058,58703,47.658590,5,5
5,21642,Sample8FOV1,174.823168,302.920155,62.287543,29338,34.575324,5,6
6,30237,Sample8FOV1,192.219202,292.856897,74.915435,32600,38.652717,5,7
7,55046,Sample8FOV1,268.002943,153.067544,75.010428,56966,47.196419,5,8
8,17277,Sample8FOV1,192.525844,205.755397,81.431730,27987,32.074254,5,9
9,30612,Sample8FOV1,215.993336,205.345061,81.246407,32318,38.811851,5,10
10,54093,Sample8FOV1,237.755625,70.091287,86.378829,55844,46.922465,5,11
11,47816,Sample8FOV1,124.795466,267.415593,90.298833,49570,45.032377,5,12
12,57601,Sample8FOV1,179.590858,108.040156,89.887189,62024,47.915622,5,13
13,44089,Sample8FOV1,103.687791,179.546894,91.684230,45710,43.830579,5,14

In [15]:
# Load
# test_df = pd.read_csv('test.csv', names=keep_columns)

In [ ]:
# check for correct number of samples
len(df_reduced)

In [17]:
# Rename columns.
for i in df_reduced:
    i.rename(columns = {'Centroid_1':'X'}, inplace = True)
    i.rename(columns = {'Centroid_2':'Y'}, inplace = True)
    i.rename(columns = {'Centroid_3':'Z'}, inplace = True)

In [21]:
df_reduced[0]

,Volume,sample_id,X,Y,Z,ConvexVolume,EquivDiameter,Pcell_id,cell_name
0,80829,Sample8FOV1,218.348699,221.575746,43.843596,85909,53.644211,5,1
1,78048,Sample8FOV1,200.770013,99.474285,50.248104,82737,53.021790,5,2
2,67871,Sample8FOV1,110.395353,225.418942,49.415170,71504,50.609092,5,3
3,62989,Sample8FOV1,126.759323,121.682992,57.744193,64928,49.365328,5,4
4,56679,Sample8FOV1,121.213783,315.551898,62.004058,58703,47.658590,5,5
5,21642,Sample8FOV1,174.823168,302.920155,62.287543,29338,34.575324,5,6
6,30237,Sample8FOV1,192.219202,292.856897,74.915435,32600,38.652717,5,7
7,55046,Sample8FOV1,268.002943,153.067544,75.010428,56966,47.196419,5,8
8,17277,Sample8FOV1,192.525844,205.755397,81.431730,27987,32.074254,5,9
9,30612,Sample8FOV1,215.993336,205.345061,81.246407,32318,38.811851,5,10
10,54093,Sample8FOV1,237.755625,70.091287,86.378829,55844,46.922465,5,11
11,47816,Sample8FOV1,124.795466,267.415593,90.298833,49570,45.032377,5,12
12,57601,Sample8FOV1,179.590858,108.040156,89.887189,62024,47.915622,5,13
13,44089,Sample8FOV1,103.687791,179.546894,91.684230,45710,43.830579,5,14

In [ ]:
# Save
np.save('df_reduced.npy', np.array(df_reduced, dtype=object), allow_pickle=True)

In [ ]:
# Load
df_reduced = np.load('df_reduced.npy', allow_pickle=True)